---
- name: Remove docker
  package:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - docker
  register: remove_packages
  retries: 10
  delay: 30
  until: remove_packages is success

- name: install specific version of docker
  include_tasks: "install_{{ docker_version_map[docker_version]['name'] }}.yml"
