---
- name: Install lvm packages
  yum:
    name: 'lvm*'
    state: present

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: true

- include_tasks: install_docker.yml
  tags: [install_docker, destructive]
