---
- name: Stop the docker service
  systemd:
    name: docker
    state: stopped

- name: Ensures /etc/systemd/system/docker.service.d dir exists
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Create service.d docker.conf
  template:
    src: docker{{ docker_version }}.conf
    dest: /etc/systemd/system/docker.service.d/docker.conf

- name: restart docker systemd
  systemd:
    name: docker
    state: restarted
    enabled: true
    daemon_reload: true

- name: stop docker systemd
  systemd:
    name: docker
    state: stopped
    enabled: false

- name: Remove var/lib/docker
  file:
    path: /var/lib/docker
    state: absent

- name: Docker daemon is enabled and systemd has read all changes
  systemd:
    name: docker
    enabled: yes
    daemon_reload: yes

